#!/bin/bash
export packagesRequired=(
  "base-devel"
  "figlet"
  "git"
  "gum"
  "python"
  "rsync"
)

export packagesPacman=(
  "alacritty"
  "blueman"
  "bluez"
  "bluez-obex"
  "bluez-utils"
  "breeze-icons"
  "brightnessctl"
  "btop"
  "bzip"
  "curl"
  "dunst"
  "exa"
  "fastfetch"
  "fd"
  "firefox"
  "fuse2"
  "grim"
  "gtk4"
  "guvcview"
  "gvfs"
  "gzip"
  "htop"
  "imagemagick"
  "imv"
  "jq"
  "lazygit"
  "libadwaita"
  "man-db"
  "man-pages"
  "meson"
  "mpv"
  "ncompress"
  "neovim"
  "network-manager-applet"
  "networkmanager"
  "nm-connection-editor"
  "nodejs"
  "noto-fonts"
  "npm"
  "onefetch"
  "otf-font-awesome"
  "pacman-contrib"
  "papirus-icon-theme"
  "pavucontrol"
  "polkit-gnome"
  "python-click"
  "python-gobject"
  "python-pip"
  "python-psutil"
  "python-pywal"
  "python-rich"
  "qalculate-gtk"
  "reflector"
  "ripgrep"
  "rust"
  "sddm"
  "sshfs"
  "sshpass"
  "tar"
  "thunar"
  "thunar-archive-plugin"
  "ttf-fira-code"
  "ttf-fira-sans"
  "ttf-firacode-nerd"
  "tumbler"
  "unrar"
  "unzip"
  "vlc"
  "waybar"
  "wget"
  "xarchiver"
  "xdg-desktop-portal"
  "xdg-user-dirs"
  "zip"
)

export packagesAUR=(
  "nvidia-open-dkms"
  "rofi-lbonn-wayland-git"
  "sddm-sugar-dark"
  "sioyek"
  "slurp"
  "topgrade"
  "wezterm"
  "wf-recorder"
  "wl-clipboard"
)

export packagesNPM=(
  "jscpd"
)

export optionalPackagesPacman=(
  "brave-bin"
  "libreoffice"
  "pdftk"               #PDF manipulating tool
  "perl-image-exiftool" #PDF metadata editor
  "torbrowser-launcher"
  "luarocks"
  "tokei"
)

export latexPacman=(
  "texlive-basic"
  "texlive-bibtexextra"
  "texlive-bin"
  "texlive-binextra"
  "texlive-context"
  "texlive-fontsrecommended"
  "texlive-fontutils"
  "texlive-formatsextra"
  "texlive-latex"
  "texlive-latexextra"
  "texlive-latexrecommended"
  "texlive-luatex"
  "texlive-metapost"
  "texlive-pictures"
  "texlive-plaingeneric"
  "texlive-pstricks"
  "texlive-publishers"
  "texlive-xetex"
)
